spring.application.name=hotel-reservas-app

spring.datasource.url=jdbc:postgresql://localhost:5433/hotel_reservas_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# http://localhost:8080/api/clientes
# http://localhost:8080/api/habitaciones